### ISSUE TITLE
Error when doing ecto.setup

### ISSUE THREAD

**Issue by DennisKo** [ryanswapp/ember-phoenix-graphql#1]
I get this when I do ecto.setup:

```
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:standard_error, :unicode, [[[], <<42, 42, 32, 40, 77, 105, 120, 41, 32, 84, 104, 101, 32, 100, 97, 116, 97, 98, 97, 115, 101, 32, 102, 111, 114, 32, 69, 109, 98, 101, 114, 80, 104, 111, 101, 110, 105, 120, 71, 114, 97, 112, 104, 113, 108, 46, 82, 101, ...>>], 10])
    (mix) lib/mix/cli.ex:67: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I can start the phoenix server but I am getting this error when navigating to posts:

```
** (ArgumentError) argument error
    (stdlib) :io.put_chars(:user, :unicode, ["[", "error", "] ", ["Postgrex.Protocol", 32, 40, "#PID<0.340.0>", ") failed to connect: " | <<42, 42, 32, 40, 80, 111, 115, 116, 103, 114, 101, 120, 46, 69, 114, 114, 111, 114, 41, 32, 70, 65, 84, 65, 76, 32, 40, 105, 110, 118, 97, 108, 105, 100, 95, 112, 97, 115, 115, 119, 111, ...>>], "\n"])
    (logger) lib/logger/backends/console.ex:29: Logger.Backends.Console.handle_event/2
    (elixir) lib/gen_event.ex:1101: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:942: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:927: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:900: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:696: GenEvent.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:gen_event_EXIT, Logger.Backends.Console, {:badarg, [{:io, :put_chars, [:user, :unicode, ["[", "error", "] ", ["Postgrex.Protocol", 32, 40, "#PID<0.340.0>", ") failed to connect: " | <<42, 42, 32, 40, 80, 111, 115, 116, 103, 114, 101, 120, 46, 69, 114, 114, 111, 114, 41, 32, 70, 65, 84, 65, 76, 32, 40, 105, 110, 118, 97, 108, ...>>], "\n"]], []}, {Logger.Backends.Console, :handle_event, 2, [file: 'lib/logger/backends/console.ex', line: 29]}, {GenEvent, :do_handler, 3, [file: 'lib/gen_event.ex', line: 1101]}, {GenEvent, :server_update, 5, [file: 'lib/gen_event.ex', line: 942]}, {GenEvent, :server_notify, 7, [file: 'lib/gen_event.ex', line: 927]}, {GenEvent, :server_event, 4, [file: 'lib/gen_event.ex', line: 900]}, {GenEvent, :handle_msg, 5, [file: 'lib/gen_event.ex', line: 696]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: {Logger, Logger.Backends.Console, #Reference<0.0.1.45>}
```

**Comment by ryanswapp** [comment]
It looks like you may not have a Postgres database server running. Can you confirm that you have Postgres up and running?

**Comment by DennisKo** [comment]
Ye it was a problem with Postgres 9.4 and 9.5 running simulataneously. Working now!

**Comment by ryanswapp** [comment]
Oh, good to hear! Glad you got it resolved :)
